---
dialect: ObjectPath
resource_uri: None

root_projection_uri: 'tests/test_dir'


bed_projection: &bed_projection
  type: file
  children: None
  name: " $.name "
  uri: " $.children[@.type is 'file' and @.extension is '.bed'].resource_uri "

vcf_projection: &vcf_projection
  type: file
  children: None
  name: " $.name "
  uri: " $.children[@.type is 'file' and @.extension is '.vcf'].resource_uri "

bam_projection: &bam_projection
  type: file
  children: None
  name: " $.name "
  uri: " $.children[@.type is 'file' and @.extension is '.bam'].resource_uri "


rerun_dir_projection: &rerun_dir_projection
  type: directory
  children:
    vcf_projection: *vcf_projection
    bed_projection: *bed_projection
  name: " content['name'] "
  uri: " [p for p in environment['children'] if fetch_context(p)['type'] == 'dir'] "

sample_dir_projection: &sample_dir_projection
  type: directory
  children:
    rerun_dir_projection: *rerun_dir_projection
    vcf_projection: *vcf_projection
    bed_projection: *bed_projection
  name: " $.name "
  uri: " $.children[@.type is 'dir'].resource_uri "

root:
  type: directory
  children:
    bam_projection: *bam_projection
    sample_dir_projection: *sample_dir_projection
  name: " $.name "
  uri: " 'tests/test_dir' "