---
dialect: python
resource_uri: http://eutils.ncbi.nlm.nih.gov'

root_projection_uri: 'query:escherichia[orgn] AND complete genome[title]:1'

fasta_file_prototype: &fasta_file_prototype
  type: file
  children: None
  name:  "'sequence.fasta'"
  uri: "['get_fasta:'+environment]"

gb_file_prototype: &gb_file_prototype
  type: file
  children: None
  name:  "'sequence.gb'"
  uri: "['get_gb:'+environment]"

root:
  type: directory
  children:
    gb_file_prototype: *gb_file_prototype
    fasta_file_prototype: *fasta_file_prototype
  name: "'GI:'+uri"
  uri: "[id for id in environment['IdList']]"