---
dialect: python
resource_uri: mockiontorrent.com
user: ionadmin
password: ionadmin

root_projection_uri: "experiment?status=run&limit=1&order_by=-id"

# Each experiment have results of run analysis associated to it, we create dir to contain this results
result_prototype: &result_prototype
  type: directory
  children: None
  name: "path.split(content['filesystempath'])[1]"
  uri: "results[]"

# Each experiment have plan associated to it, so we create plan metadata prototype
exp_plan_metadata_prototype: &exp_plan_metadata_prototype
  type: file
  children: None
  name:  "'plannedexperiment.json'"
  uri: "plan"

# Metadata for root projection
exp_metadata_prototype: &exp_metadata_prototype
  type: file
  children: None
  name:  "'metadata.json'"
  uri: "resource_uri"

root:
  type: directory
  children:
    exp_metadata_prototype: *exp_metadata_prototype
    exp_plan_metadata_prototype: *exp_plan_metadata_prototype
    result_prototype: *result_prototype
  name: "content['displayName'].replace(' ', '_')"
  uri: "objects[].resource_uri"
