---
# This is example configuration of filesystem projection.
# This projection uses python as it`s microcode
dialect: python
resource_uri: None

# Root projection uri is dir which contents we will project
root_projection_uri: 'tests/test_dir'

# BED file projection
bed_projection: &bed_projection
  type: file
  children: None
  name: " content['name'] "
  uri: " [p for p in environment['children'] if fetch_context(p)['type'] == 'file' and fetch_context(p)['extension'] == '.bed'] "

# VCF file projection
vcf_projection: &vcf_projection
  type: file
  children: None
  name: " content['name'] "
  uri: " [p for p in environment['children'] if fetch_context(p)['type'] == 'file' and fetch_context(p)['extension'] == '.vcf'] "

# BAM file projection
bam_projection: &bam_projection
  type: file
  children: None
  name: " content['name'] "
  uri: " [p for p in environment['children'] if fetch_context(p)['type'] == 'file' and fetch_context(p)['extension'] == '.bam'] "

# Projection of test samples
sample_dir_projection: &sample_dir_projection
  type: directory
  children:
    vcf_projection: *vcf_projection
    bed_projection: *bed_projection
  name: " content['name'] "
  uri: " [p for p in environment['children'] if fetch_context(p)['type'] == 'dir'] "

# Root dir for projection contents
root:
  type: directory
  children:
    bam_projection: *bam_projection
    sample_dir_projection: *sample_dir_projection
  name: " content['name'] "
  uri: "[ parent_projection.uri ]"