---
dialect: ObjectPath
resource_uri: http://eutils.ncbi.nlm.nih.gov

root_projection_uri: 'search_query:escherichia[orgn] AND complete genome[title]:3'

fasta_file_prototype: &fasta_file_prototype
  type: file
  children: None
  name: " join([$.resource_uri, 'sequence.fasta'], '_' )"
  uri: " $.fasta_files "

gb_file_prototype: &gb_file_prototype
  type: file
  children: None
  name: " join([$.resource_uri, 'sequence.fasta'], '_' ) "
  uri: " $.gb_files "

root:
  type: transparent
  children:
    gb_file_prototype: *gb_file_prototype
    fasta_file_prototype: *fasta_file_prototype
  name: " $.resource_uri "
  uri: " 'search_query:escherichia[orgn] AND complete genome[title]:3' "
