---
# Genbank projection example

dialect: python
resource_uri: http://eutils.ncbi.nlm.nih.gov

# Root projection URI is query to nuccore database. It fully supports Entrez search syntax. 
root_projection_uri: 'query:escherichia[orgn] AND complete genome[title]:5'

# Fasta file prototype
fasta_file_prototype: &fasta_file_prototype
  type: file
  children: None
  name:  "'sequence.fasta'"
  uri: "['get_fasta:'+environment['id']]"

# Prototype of gb file
gb_file_prototype: &gb_file_prototype
  type: file
  children: None
  name:  "'sequence.gb'"
  uri: "['get_gb:'+environment['id']]"

# Directory corresponding to GI wich holds fasta and gb files
root:
  type: directory
  children:
    gb_file_prototype: *gb_file_prototype
    fasta_file_prototype: *fasta_file_prototype
  name: "'GI:'+uri"
  uri: "[id for id in environment['IdList']]"
