---
# This is example configuration of SRA projection.
# This projection uses ObjectPath as it`s microcode
dialect: ObjectPath
resource_uri: http://eutils.ncbi.nlm.nih.gov'

# Root projection us query to Entrez eutils esearch, this enables user to enter desired search query to search SRA
# database and project search results.
# SRA driver supports use of Entrez search syntax, which allows to create elaborate filters, here we specify
# creation of projection of experiments with Homo Sapiens as organism, which contain brain and tumor in fields.
root_projection_uri: 'query:Human[Organism] AND Brain[All Fields] AND Tumor[All Fields]:3'

# Prototype of run, projects to SAM file which corresponds to experiment
run_prototype: &run_prototype
  type: file
  children: None
  name:  " $.@accession + '.sam' "
  uri: " $.EXPERIMENT_PACKAGE_SET.EXPERIMENT_PACKAGE.RUN_SET.RUN.@accession "

# Prototype of experiment metadata, projects to json file
experiment_meta_prototype: &experiment_meta_prototype
  type: file
  children: None
  name:  " $.@accession + '.sam' + '.meta' "
  uri: " $.resource_uri "

# This is a root prototype for projections, its context will be used as environment for children prototypes
root:
  type: directory
  children:
    experiment_meta_prototype: *experiment_meta_prototype
    run_prototype: *run_prototype
  name: " $.environment.QueryTranslation "
  uri: " $.IdList "