---
dialect: ObjectPath
resource_uri: None

root_projection_uri: 'tests/mock_resources/miseq_mock_data'

sample_sheet_projection: &sample_sheet_projection
  type: file
  children: None
  name: " $.name "
  uri: " $.children[@.type is 'file' and @.extension is '.bai' and 'SampleSheet' in @.name].resource_uri "

bam_projection: &bam_projection
  type: file
  children: None
  name: " $.name "
  uri: " $.children[@.type is 'file' and @.extension is '.bam'].resource_uri "

bai_projection: &bai_projection
  type: file
  children: None
  name: " $.name "
  uri: " $.children[@.type is 'file' and @.extension is '.bai'].resource_uri "

alignment_dir_projection: &alignment_dir_projection
  type: transparent
  children:
    bai_projection: *bai_projection
    bam_projection: *bam_projection
    sample_sheet_projection: *sample_sheet_projection
  name: " $.name "
  uri: " $.children[@.type is 'dir' and 'Alignment' in @.name].resource_uri "

base_call_dir_projection: &base_call_dir_projection
  type: transparent
  children:
    alignment_dir_projection: *alignment_dir_projection
  name: " $.name "
  uri: " $.children[@.type is 'dir' and 'BaseCalls' in @.name].resource_uri "

intensities_dir_projection: &intensities_dir_projection
  type: transparent
  children:
    base_call_dir_projection: *base_call_dir_projection
  name: " $.name "
  uri: " $.children[@.type is 'dir' and 'Intensities' in @.name].resource_uri"

data_dir_projection: &data_projection
  type: transparent
  children:
    intensities_dir_projection: *intensities_dir_projection
  name: " $.name "
  uri: " $.children[@.type is 'dir' and 'Data' in @.name].resource_uri "

run_projection: &run_projection
  type: directory
  children:
    data_projection: *data_projection
  name: " $.name "
  uri: " $.children[@.type is 'dir' and 'M70294' in @.name].resource_uri "

root:
  type: directory
  children:
    run_projection: *run_projection
  name: " $.name "
  uri: " $.children[@.name is 'data'].resource_uri "